Repository woowa-techcamp-2021/deal-1, pull requests merged in 2021-07, with the labels that each got.

#4 webpack 설정하였습니다.
  .gitignore
  asset/view/.keep
  asset/view/login.js
  package-lock.json
  package.json
  views/index.jade
  webpack.config.js
Labels: env

#6 feature - 자동 refresh code 추가
  app.js
  asset/view/login.js
  package-lock.json
  package.json
  webpack.config.js
Labels: env

#7 feature - webpack loader plugin 적용
  app.js
  asset/view/login.js
  package-lock.json
  package.json
  public/css/style.css
  views/index.jade
  views/layout.jade
  webpack.config.js
Labels: env

#8 디렉토리 구조 변화
  .gitignore
  app.js
  asset/css/.keep
  asset/css/test.css
  asset/view/login.js
  package-lock.json
  routes/index.js
  views/login.html
  webpack.config.js
Labels: env

#54 feature - 자동 reload 기능 구현했습니다.
  app.js
  asset/globalInit.js
  asset/view/login.js
  package-lock.json
  package.json
  routes/index.js
  routes/login.js
  views/error.jade
  views/index.jade
  views/layout.jade
  views/login.html
  webpack.config.js
Labels: env

#55 feature - Lint 와 Prettier 기능 구현
  .babelrc
  .eslintrc.json
  .prettierrc.json
  .vscode/settings.json
  package-lock.json
  package.json
Labels: env

#59 fix - dir 구조 변경 했습니다.
  app.js
  asset/pages/index.js
  routes/index.js
  routes/login.js
  routes/users.js
  views/index.html
  webpack.config.js
Labels: env

#60 feature - devtools : SOURCE MAP 추가했습니다.
  asset/pages/index.js
  package-lock.json
  webpack.config.js
Labels: env

#61 feature - app container 추가했습니다.
  asset/css/common.css
  asset/pages/index.js
  views/index.html
Labels: env

#62 feature - Router
  asset/component/PageElement.js
  asset/css/common.css
  asset/css/test.css
  asset/pages/Test/index.js
  asset/pages/index.js
  asset/router.js
Labels: frontend

#63 feature - main page UI 구현
  .DS_Store
  asset/component/.keep
  asset/component/FaB.js
  asset/component/Image.js
  asset/component/ListItem.js
  asset/component/MainHeader.js
  asset/component/icons.js
  asset/css/common.css
  asset/css/fab.css
  asset/css/listItem.css
  asset/css/mainheader.css
  asset/css/normalize.css
  asset/pages/index.js
  asset/util/domControll.js
  public/.DS_Store
  public/resource/.DS_Store
  public/resource/category.svg
  public/resource/chat.svg
  public/resource/like.svg
  public/resource/mapPin.svg
  public/resource/menu.svg
  public/resource/plus.svg
  public/resource/user.svg
Labels: frontend

#64 feature - Element Component에 대한 자세한 설계
  asset/component/ElementBuilder.js
  asset/component/PageElement.js
  asset/css/common.css
  asset/pages/Test/TestTextComponent.js
  asset/pages/Test/index.js
  asset/pages/index.js
  asset/router.js
Labels: frontend

#65 fix - Router와 ElementBuilder, icon 등 연동
  asset/component/ElementBuilder.js
  asset/component/FaB.js
  asset/component/MainHeader.js
  asset/component/icons.js
  asset/css/common.css
  asset/css/mainheader.css
  asset/pages/Test/index.js
  asset/pages/index.js
  asset/router.js
Labels: bug, frontend

#67 feature - input component 만들었습니다.
  asset/component/Input/index.js
  asset/css/input.css
  asset/pages/Test/index.js
  public/.DS_Store
Labels: frontend

#69 feature - 카테고리 페이지 구현했습니다.
  asset/component/MainHeader.js
  asset/component/SubHeader.js
  asset/component/icons.js
  asset/css/categoryBody.css
  asset/css/main.css
  asset/css/mainheader.css
  asset/css/subHeader.css
  asset/pages/Category/CategoryBody.js
  asset/pages/Category/index.js
  asset/pages/Main/index.js
  asset/pages/index.js
  public/resource/back.svg
Labels: frontend

#73 feature - 이미지 업로드 기능
  asset/component/ImageBtn.js
  asset/component/icons.js
  asset/css/common.css
  asset/css/write.css
  asset/pages/Write/ImageUploader.js
  asset/pages/Write/index.js
  asset/pages/index.js
  public/resource/delete.svg
  public/resource/picture.svg
Labels: frontend

#70 feature - Button Component 추가했습니다.
  .DS_Store
  asset/component/button/index.js
  asset/css/button.css
  asset/css/input.css
  asset/css/test.css
  asset/pages/Test/index.js
Labels: frontend

#72 fix - elementBuilder에서 init을 좀 더 추상화하였습니다.
  asset/component/ElementBuilder.js
  asset/component/FaB.js
  asset/component/Input/index.js
  asset/component/MainHeader.js
  asset/component/SubHeader.js
  asset/pages/Category/CategoryBody.js
  asset/pages/Category/index.js
  asset/pages/Main/index.js
  asset/pages/Test/TestTextComponent.js
  asset/pages/Test/index.js
  asset/router.js
Labels: additional, enhancement, frontend

#74 feature - setState 구현
  asset/component/ElementBuilder.js
  asset/component/button/index.js
  asset/pages/Write/ImageUploader.js
  asset/pages/Write/index.js
  asset/pages/index.js
Labels: enhancement, frontend

#77 feature - update 함수 구현
  asset/component/ElementBuilder.js
  asset/css/write.css
  asset/pages/Write/ImageUploader.js
  asset/pages/Write/WriteContainer.js
  asset/pages/Write/index.js
Labels: bug, frontend

#79 feature - 회원가입 페이지 구현
  asset/component/Button.js
  asset/component/Input.js
  asset/css/input.css
  asset/css/login.css
  asset/css/normalize.css
  asset/css/register.css
  asset/pages/Login/LoginContainer.js
  asset/pages/Login/index.js
  asset/pages/Register/RegisterContainer.js
  asset/pages/Register/index.js
  asset/pages/Write/WriteContainer.js
  asset/pages/index.js
Labels: frontend

#80 feature - write page 개발했습니다.
  .eslintrc.json
  asset/component/Button.js
  asset/component/CategoryButton.js
  asset/component/CategoryList.js
  asset/component/CategorySelector.js
  asset/component/CategorySelectorContainer.js
  asset/component/DivLine.js
  asset/component/ImageBtn.js
  asset/component/TextAreaInput.js
  asset/component/TextInput.js
  asset/component/TitleTextInput.js
  asset/component/WriteBottomFotter.js
  asset/component/icons.js
  asset/css/button.css
  asset/css/common.css
  asset/css/textInput.css
  asset/css/write.css
  asset/pages/Write/ImageUploader.js
  asset/pages/Write/WriteContainer.js
  public/resource/mapPin.png
Labels: frontend

#83 feature - 메뉴 탭 구현
  asset/component/ListItem.js
  asset/component/SubHeader.js
  asset/css/common.css
  asset/css/listItem.css
  asset/css/menu.css
  asset/css/product.css
  asset/css/subHeader.css
  asset/pages/Main/index.js
  asset/pages/Menu/MenuContainer.js
  asset/pages/Menu/Tabs/ChattingList/ChatListItem.js
  asset/pages/Menu/Tabs/ChattingList/index.js
  asset/pages/Menu/Tabs/LikeList.js
  asset/pages/Menu/Tabs/SellingList.js
  asset/pages/Menu/index.js
  asset/pages/Product/index.js
  asset/util/tempList.js
  asset/util/utlls.js
  public/.DS_Store
  public/resource/.DS_Store
  public/resource/blueFan.png
  public/resource/lamp.png
  public/resource/leaves.png
  public/resource/like__small.png
  public/resource/mirror.png
  public/resource/poetry.png
  public/resource/roller1.png
  public/resource/roller2.png
  public/resource/roller3.png
Labels: frontend

#85 feature - category page add
  asset/component/CategoryImage.js
  asset/pages/Category/CategoryBody.js
  asset/pages/Category/index.js
  public/resource/book.png
  public/resource/clothe.png
  public/resource/digital.png
  public/resource/etc.png
  public/resource/food.png
  public/resource/furniture.png
  public/resource/game.png
  public/resource/kids.png
  public/resource/life.png
  public/resource/pet.png
  public/resource/plant.png
  public/resource/skirt.png
  public/resource/sport.png
  public/resource/veauti.png
Labels: frontend

#86 feature - loading animation 구현.
  asset/component/LoadingModal.js
  asset/css/categoryBody.css
  asset/css/modal.css
  asset/pages/Category/index.js
  asset/pages/Main/index.js
  asset/router.js
  public/resource/app-title.png
  public/resource/logo.png
Labels: additional, frontend

#87 fix - main header reanme
  asset/css/mainHeader.css
Labels: bug

#88 feature - dropdown 구현했습니다.
  asset/component/DropDown.js
  asset/component/FaB.js
  asset/component/IconButtons.js
  asset/component/ImageBtn.js
  asset/component/ListItem.js
  asset/component/MainHeader.js
  asset/component/SubHeader.js
  asset/component/WriteBottomFotter.js
  asset/css/dropDown.css
  asset/css/mainHeader.css
  asset/pages/Main/index.js
  asset/util/domControll.js
Labels: frontend

#108 fix - write page 여러 기능 추가 및 수정
  asset/component/CategorySelector.js
  asset/component/CategorySelectorContainer.js
  asset/component/ListItem.js
  asset/component/TextAreaInput.js
  asset/component/TextInput.js
  asset/component/TitleTextInput.js
  asset/pages/Main/index.js
  asset/pages/Write/WriteContainer.js
  asset/pages/index.js
  asset/util/utils.js
  asset/util/utlls.js
  package-lock.json
Labels: bug, frontend

#103 feature - WebSocket을 편하게 사용하기 위한 Router를 개발했습니다.
  app.js
  bin/www
  package-lock.json
  package.json
  public/.DS_Store
  public/resource/.DS_Store
  routes/clientTestFile.js
  routes/webSocket.js
  webSocketApp.js
Labels: additional, backend

#109 feature - db modeling 한 자료 올렸습니다.
  PROJ_INFO/deal1 ERD.png
  model/query/createTable.sql
Labels: additional, backend

#111 fix - main page / Router / MainHeader
  asset/component/ElementBuilder.js
  asset/component/MainHeader.js
  asset/css/main.css
  asset/css/mainHeader.css
  asset/pages/Main/index.js
  asset/router.js
Labels: bug, frontend

#113 fix - project infor
  PROJ_INFO/우아마켓 로고와 글자.png
  README.md
  model/query/createTable.sql
Labels: additional, documentation

#114 feature - 메인 페이지 api 연동
  .DS_Store
  app.js
  asset/component/ElementBuilder.js
  asset/component/ListItem.js
  asset/pages/Main/index.js
  asset/pages/Product/ProductContainer.js
  model/query/auth.js
  model/query/products.js
  public/.DS_Store
  public/resource/productImg/roller1.png
  routes/products.js
Labels: frontend

#118 feature - modal 구현했습니다.
  asset/component/Alert.js
  asset/component/InputPopUp.js
  asset/css/modal.css
Labels: frontend

#104 feature - chatting UI 구현
  asset/component/ChatMsg.js
  asset/component/ElementBuilder.js
  asset/component/IconButtons.js
  asset/component/Input.js
  asset/css/chatMsg.css
  asset/css/chattingRoom.css
  asset/pages/ChattingRoom/Chat/ChatInput.js
  asset/pages/ChattingRoom/Chat/ChatLog.js
  asset/pages/ChattingRoom/Chat/index.js
  asset/pages/ChattingRoom/ChattingRoomContainer.js
  asset/pages/ChattingRoom/ProductStatusHeader.js
  asset/pages/ChattingRoom/index.js
  asset/pages/Menu/MenuContainer.js
  asset/pages/Menu/Tabs/ChattingList/ChatListItem.js
  asset/pages/Menu/Tabs/ChattingList/index.js
  asset/pages/Menu/index.js
  asset/pages/index.js
  public/resource/send.svg
Labels: frontend

#125 feature - web socket을 사용한 Chatting 기능 구현했습니다.
  backend/lib/WebSocketRouter.js
  backend/lib/webSocketApp.js
  backend/routes/chat.js
  public/.DS_Store
Labels: backend

#124 fix - fetch with wait until.
  frontend/util/api.js
Labels: enhancement, frontend

#123 feature - 동네 추가 삭제창 구현했습니다.
  frontend/component/DropDown/DropDown.js
  frontend/component/MainHeader/MainHeader.js
  frontend/component/MainHeader/mainHeader.css
  frontend/component/Modal/Alert.js
  frontend/component/Modal/InputPopUp.js
  frontend/constant/imgSrc.js
  frontend/constant/strings.js
  frontend/pages/ChattingRoom/index.js
  frontend/pages/Location/LocationTitleContainer.js
  frontend/pages/Location/index.js
  frontend/pages/Location/location.css
  frontend/pages/Location/locationButton.js
  frontend/pages/Location/locationButtonContainer.js
  frontend/pages/Main/index.js
  public/.DS_Store
  public/resource/.DS_Store
  public/resource/cancle.png
  public/resource/pet.png
  public/resource/plus.png
Labels: frontend

#122 fix - loading modal에서 로딩 다 하고 Main으로 넘어가게 변경.
  frontend/component/Modal/LoadingModal.js
  frontend/lib/router.js
  frontend/pages/Loading/index.js
  frontend/pages/Loading/loading.css
  frontend/pages/Main/index.js
  frontend/pages/index.js
  package-lock.json
Labels: bug, frontend

#128 fix - 메뉴 아이템 드롭다운 추가
  frontend/component/Button/IconButtons.js
  frontend/component/DropDown/DropDown.js
  frontend/component/DropDown/dropdown.css
  frontend/component/ListItem/ListItem.js
  frontend/component/ListItem/listItem.css
  frontend/component/MainHeader/MainHeader.js
  frontend/pages/Loading/index.js
  frontend/pages/Menu/Tabs/SellingList.js
  public/resource/dot.svg
Labels: frontend

#129 feature - 좋아요 버튼 구현
  backend/model/query/products.js
  backend/routes/products.js
  frontend/component/Button/button.css
  frontend/component/ListItem/ListItem.js
  frontend/pages/Loading/index.js
  frontend/pages/Main/index.js
  frontend/pages/Menu/MenuContainer.js
  frontend/pages/Menu/Tabs/LikeList.js
  frontend/pages/Menu/Tabs/SellingList.js
Labels: backend, frontend

#130 Feature - main 로그인 체크 함수
  app.js
  backend/lib/constant.js
  backend/lib/util.js
  backend/middleware/auth.js
  backend/routes/auth.js
  backend/routes/nonAuth.js
  backend/routes/products.js
  backend/routes/profile.js
  frontend/component/ListItem/ListItem.js
  frontend/lib/ElementBuilder.js
  frontend/lib/commonCSS/common.css
  frontend/pages/Loading/index.js
  frontend/pages/Login/LoginContainer.js
  frontend/pages/Login/index.js
  frontend/pages/Logout/LogoutContainer.js
  frontend/pages/Main/DragDownItem.js
  frontend/pages/Main/index.js
  frontend/pages/Main/main.css
  frontend/pages/index.js
  frontend/util/api.js
  package-lock.json
  package.json
Labels: additional, backend, frontend

#133 feature - 제품상세보기
  .DS_Store
  app.js
  backend/model/query/categories.js
  backend/model/query/products.js
  backend/routes/products.js
  frontend/component/ListItem/ListItem.js
  frontend/pages/ChattingRoom/Chat/ChatInput.js
  frontend/pages/ChattingRoom/Chat/index.js
  frontend/pages/Main/index.js
  frontend/pages/Menu/MenuContainer.js
  frontend/pages/Product/ProductBar.js
  frontend/pages/Product/ProductContainer.js
  frontend/pages/Product/ProductContent.js
  frontend/pages/Product/SlidingImageShower.js
  frontend/pages/Product/index.js
  frontend/pages/Write/TextAreaInput.js
  frontend/pages/Write/TextInput.js
  frontend/pages/Write/TitleTextInput.js
  frontend/pages/Write/index.js
  public/.DS_Store
  public/resource/.DS_Store
Labels: bug, frontend

#134 fix - UI와 여러 버그 수정했습니다.
  backend/lib/WebSocketRouter.js
  backend/routes/location.js
  frontend/component/Input/input.css
  frontend/component/MainHeader/MainHeader.js
  frontend/lib/router.js
  frontend/pages/Login/LoginContainer.js
  frontend/pages/Logout/LogoutContainer.js
  frontend/pages/Main/index.js
  frontend/pages/Menu/Tabs/ChattingList/index.js
  frontend/pages/Menu/menu.css
  frontend/util/api.js
Labels: bug, frontend

#135 feature - 삭제기능 구현
  backend/model/query/createTable.sql
  backend/model/query/products.js
  backend/routes/products.js
  frontend/component/ListItem/ListItem.js
  frontend/pages/Main/index.js
  frontend/pages/Menu/MenuContainer.js
  frontend/pages/Menu/Tabs/SellingList.js
  frontend/pages/Menu/menu.css
  frontend/pages/Write/index.js
  frontend/util/utils.js
  public/.DS_Store
  public/resource/.DS_Store
Labels: backend

#136 feature - 상품 상세창
  Ellipse 28.svg
  backend/model/query/products.js
  backend/routes/nonAuth.js
  backend/routes/products.js
  frontend/component/Modal/SpinnerModal.js
  frontend/component/Modal/modal.css
  frontend/lib/ElementBuilder.js
  frontend/pages/Main/index.js
  frontend/pages/Product/ProductBar.js
  frontend/pages/Product/ProductContainer.js
  frontend/pages/Product/SellerButton.js
  frontend/pages/Product/SellerDropDown.js
  frontend/pages/Product/index.js
  frontend/pages/Product/product.css
  frontend/pages/Write/index.js
  public/.DS_Store
  public/resource/.DS_Store
  public/resource/down.png
Labels: frontend

#137 feature - 글쓰기 수정 기능
  backend/model/query/products.js
  backend/routes/products.js
  frontend/component/Button/button.css
  frontend/component/ListItem/ListItem.js
  frontend/component/Modal/Alert.js
  frontend/pages/Main/index.js
  frontend/pages/Menu/MenuContainer.js
  frontend/pages/Menu/Tabs/SellingList.js
  frontend/pages/Write/TextInput.js
  frontend/pages/Write/index.js
  package-lock.json
Labels: frontend

#138 feature - 채팅 구현
  app.js
  backend/lib/WebSocketRouter.js
  backend/lib/constant.js
  backend/model/query/chat.js
  backend/model/query/createTable.sql
  backend/routes/auth.js
  backend/routes/chat.js
  backend/routes/expressChat.js
  frontend/pages/ChattingRoom/Chat/index.js
  frontend/pages/ChattingRoom/ChattingRoomContainer.js
  frontend/pages/ChattingRoom/ProductStatusHeader.js
  frontend/pages/ChattingRoom/index.js
  frontend/pages/Menu/Tabs/ChattingList/ChatListItem.js
  frontend/pages/Menu/Tabs/ChattingList/index.js
  frontend/pages/Product/ProductBar.js
  frontend/pages/Product/index.js
  frontend/util/webSocketApi.js
Labels: additional, frontend
